name: Api CI Workflow

on:
  pull_request:
    branches: [ "**" ]
    paths:
      - "api/**"
  push:
    branches: [ "main","release" ]
    paths:
      - "api/**"

permissions:
  contents: read
jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"

    - name: Build Test Containers
      run: docker-compose build api_test

    - name: Test with pytest and generate coverage report
      id: coverage-report
      run: |
        docker-compose run api_test pipenv run coverage run -m pytest
        report="$(
          docker-compose run api_test pipenv run coverage report --sort=cover)"
        echo "COVERAGE_REPORT="$report"" >> $GITHUB_OUTPUT

    - name: Run coverage commenter
      uses: grant0711/pytest-coverage-commenter@main
      with:
        service-name: 'API'
        coverage-report: ${{ steps.coverage-report.outputs.COVERAGE_REPORT }}
        github-token: ${{ secrets.GITHUB_TOKEN }}